import {
  db,
  brandsTable,
  categoriesTable,
  productsTable,
  testimonialsTable,
  type InsertProduct,
  type InsertCategory,
  type InsertBrand,
  type InsertTestimonial,
} from "@workspace/db";

const categories: InsertCategory[] = [
  {
    slug: "fashion",
    name: "Fashion",
    image: "cat-fashion.png",
    icon: "Shirt",
    position: 1,
  },
  {
    slug: "mobiles",
    name: "Mobiles",
    image: "product-phone.png",
    icon: "Smartphone",
    position: 2,
  },
  {
    slug: "electronics",
    name: "Electronics",
    image: "product-ac.png",
    icon: "Tv",
    position: 3,
  },
  {
    slug: "grocery",
    name: "Grocery",
    image: "cat-grocery.png",
    icon: "ShoppingBasket",
    position: 4,
  },
  {
    slug: "home-lifestyle",
    name: "Home & Lifestyle",
    image: "promo-band-1.jpg",
    icon: "Home",
    position: 5,
  },
  {
    slug: "beauty",
    name: "Beauty",
    image: "promo-band-2.jpg",
    icon: "Sparkles",
    position: 6,
  },
  {
    slug: "mother-baby",
    name: "Mother & Baby",
    image: "summer-edit.jpg",
    icon: "Baby",
    position: 7,
  },
];

const brands: InsertBrand[] = [
  { slug: "khaadi", name: "Khaadi", position: 1 },
  { slug: "gul-ahmed", name: "Gul Ahmed", position: 2 },
  { slug: "sapphire", name: "Sapphire", position: 3 },
  { slug: "alkaram", name: "Alkaram Studio", position: 4 },
  { slug: "samsung", name: "Samsung", position: 5 },
  { slug: "infinix", name: "Infinix", position: 6 },
  { slug: "xiaomi", name: "Xiaomi", position: 7 },
  { slug: "haier", name: "Haier", position: 8 },
  { slug: "dawlance", name: "Dawlance", position: 9 },
  { slug: "national", name: "National Foods", position: 10 },
  { slug: "shan", name: "Shan Foods", position: 11 },
  { slug: "tapal", name: "Tapal", position: 12 },
  { slug: "service", name: "Service Shoes", position: 13 },
  { slug: "borjan", name: "Borjan", position: 14 },
];

const products: InsertProduct[] = [
  {
    slug: "khaadi-printed-lawn-three-piece-summer-2026",
    name: "Printed Lawn Three Piece — Summer Edit 2026",
    brandSlug: "khaadi",
    categorySlug: "fashion",
    description:
      "Hand-finished printed lawn three piece with intricate block-print motifs, organza dupatta, and dyed cambric trousers. Designed in Karachi for Pakistan's hottest months.",
    price: 6490,
    oldPrice: 8990,
    image: "product-khaadi.png",
    images: ["product-khaadi.png", "promo-fashion.png", "summer-edit.jpg"],
    rating: "4.8",
    reviewCount: 1284,
    stock: 42,
    sold: 3210,
    isFlashDeal: true,
    isNew: true,
    isFeatured: true,
    tags: ["lawn", "summer", "unstitched"],
  },
  {
    slug: "gul-ahmed-embroidered-chiffon-festive",
    name: "Embroidered Chiffon Festive Suit",
    brandSlug: "gul-ahmed",
    categorySlug: "fashion",
    description:
      "Three-piece embroidered chiffon with sequinned bodice, raw silk trouser, and pure chiffon dupatta. Perfect for Eid evenings and family functions.",
    price: 12990,
    oldPrice: 15990,
    image: "promo-fashion.png",
    images: ["promo-fashion.png", "product-khaadi.png"],
    rating: "4.7",
    reviewCount: 642,
    stock: 28,
    sold: 1180,
    isFlashDeal: false,
    isNew: true,
    isFeatured: true,
    tags: ["festive", "eid", "chiffon"],
  },
  {
    slug: "sapphire-cotton-kurti-tropical",
    name: "Tropical Print Cotton Kurti",
    brandSlug: "sapphire",
    categorySlug: "fashion",
    description:
      "Lightweight cotton kurti in a vivid tropical print. Relaxed straight cut with side slits — pairs with denim or palazzo.",
    price: 2990,
    oldPrice: 3990,
    image: "summer-edit.jpg",
    images: ["summer-edit.jpg", "promo-fashion.png"],
    rating: "4.6",
    reviewCount: 520,
    stock: 86,
    sold: 2410,
    isFlashDeal: false,
    isNew: false,
    isFeatured: true,
    tags: ["kurti", "summer", "casual"],
  },
  {
    slug: "alkaram-mens-lawn-shalwar-kameez",
    name: "Men's Premium Lawn Shalwar Kameez",
    brandSlug: "alkaram",
    categorySlug: "fashion",
    description:
      "Premium summer lawn for men in classic ivory. Stitched with hidden placket and self collar. Wash-friendly and crease-resistant.",
    price: 4290,
    oldPrice: 5490,
    image: "promo-band-1.jpg",
    images: ["promo-band-1.jpg"],
    rating: "4.5",
    reviewCount: 312,
    stock: 64,
    sold: 980,
    isFlashDeal: false,
    isNew: false,
    isFeatured: false,
    tags: ["mens", "lawn", "stitched"],
  },
  {
    slug: "service-leather-loafers-cognac",
    name: "Hand-Stitched Leather Loafers — Cognac",
    brandSlug: "service",
    categorySlug: "fashion",
    description:
      "Full-grain leather loafers, hand-stitched in Lahore. Memory-foam insole and rubber sole built for everyday wear.",
    price: 5490,
    oldPrice: 6990,
    image: "product-shoes.png",
    images: ["product-shoes.png"],
    rating: "4.7",
    reviewCount: 880,
    stock: 35,
    sold: 1520,
    isFlashDeal: true,
    isNew: false,
    isFeatured: true,
    tags: ["shoes", "leather", "mens"],
  },
  {
    slug: "borjan-kolhapuri-chappals-tan",
    name: "Kolhapuri Chappals — Tan",
    brandSlug: "borjan",
    categorySlug: "fashion",
    description:
      "Traditional kolhapuri chappals in vegetable-tanned tan leather. Open weave, breathable, hand-finished.",
    price: 2490,
    oldPrice: null,
    image: "product-shoes.png",
    images: ["product-shoes.png"],
    rating: "4.4",
    reviewCount: 226,
    stock: 110,
    sold: 640,
    isFlashDeal: false,
    isNew: true,
    isFeatured: false,
    tags: ["chappals", "casual"],
  },
  {
    slug: "samsung-galaxy-a55-5g-256gb",
    name: "Samsung Galaxy A55 5G (8/256GB)",
    brandSlug: "samsung",
    categorySlug: "mobiles",
    description:
      "6.6\" Super AMOLED, Exynos 1480, 50MP OIS triple camera. Official PTA-approved warranty across Pakistan.",
    price: 124999,
    oldPrice: 139999,
    image: "product-phone.png",
    images: ["product-phone.png"],
    rating: "4.7",
    reviewCount: 412,
    stock: 22,
    sold: 540,
    isFlashDeal: true,
    isNew: true,
    isFeatured: true,
    tags: ["5g", "amoled", "pta"],
  },
  {
    slug: "infinix-note-40-pro",
    name: "Infinix Note 40 Pro (8/256GB)",
    brandSlug: "infinix",
    categorySlug: "mobiles",
    description:
      "Curved AMOLED, 100W fast charge with magnetic wireless pad, Helio G99 Ultimate. 7-day standby.",
    price: 67999,
    oldPrice: 74999,
    image: "product-phone.png",
    images: ["product-phone.png"],
    rating: "4.5",
    reviewCount: 318,
    stock: 48,
    sold: 1280,
    isFlashDeal: false,
    isNew: true,
    isFeatured: true,
    tags: ["amoled", "fast-charge"],
  },
  {
    slug: "xiaomi-redmi-13c-128gb",
    name: "Redmi 13C (6/128GB)",
    brandSlug: "xiaomi",
    categorySlug: "mobiles",
    description:
      "Big-battery everyday phone with 50MP camera, 90Hz display and side-mount fingerprint. PTA approved.",
    price: 32999,
    oldPrice: 36999,
    image: "product-phone.png",
    images: ["product-phone.png"],
    rating: "4.3",
    reviewCount: 524,
    stock: 96,
    sold: 2140,
    isFlashDeal: true,
    isNew: false,
    isFeatured: false,
    tags: ["budget", "battery"],
  },
  {
    slug: "haier-1-5-ton-inverter-ac-hsu-18hfca",
    name: "Haier 1.5 Ton DC Inverter AC HSU-18HFCA",
    brandSlug: "haier",
    categorySlug: "electronics",
    description:
      "75% energy saving DC inverter with turbo cooling, self-clean and 10-year compressor warranty. Made for Pakistani summers.",
    price: 184999,
    oldPrice: 209999,
    image: "product-ac.png",
    images: ["product-ac.png"],
    rating: "4.6",
    reviewCount: 219,
    stock: 14,
    sold: 380,
    isFlashDeal: true,
    isNew: false,
    isFeatured: true,
    tags: ["ac", "inverter", "summer"],
  },
  {
    slug: "dawlance-1-ton-inverter-ac-elegance-15",
    name: "Dawlance 1 Ton Inverter AC Elegance Plus 15",
    brandSlug: "dawlance",
    categorySlug: "electronics",
    description:
      "Slim-fit inverter AC with eco mode, gentle-cool and double-protection filter. Local service network in 60+ cities.",
    price: 169999,
    oldPrice: 189999,
    image: "product-ac.png",
    images: ["product-ac.png"],
    rating: "4.5",
    reviewCount: 142,
    stock: 18,
    sold: 260,
    isFlashDeal: false,
    isNew: true,
    isFeatured: true,
    tags: ["ac", "inverter"],
  },
  {
    slug: "samsung-43-crystal-uhd-4k-tv",
    name: "Samsung 43\" Crystal UHD 4K Smart TV",
    brandSlug: "samsung",
    categorySlug: "electronics",
    description:
      "PurColor, HDR, Crystal Processor 4K and Tizen smart hub with built-in YouTube, Netflix and Tapmad.",
    price: 119999,
    oldPrice: 134999,
    image: "promo-band-2.jpg",
    images: ["promo-band-2.jpg"],
    rating: "4.6",
    reviewCount: 188,
    stock: 24,
    sold: 410,
    isFlashDeal: false,
    isNew: false,
    isFeatured: true,
    tags: ["tv", "4k", "smart"],
  },
  {
    slug: "national-mango-pickle-1kg",
    name: "Punjabi Mango Pickle (Achar) 1kg",
    brandSlug: "national",
    categorySlug: "grocery",
    description:
      "Sun-cured raw mango pickle in mustard oil with traditional Punjabi spices. No artificial preservatives.",
    price: 690,
    oldPrice: 890,
    image: "product-pickle.png",
    images: ["product-pickle.png"],
    rating: "4.8",
    reviewCount: 1620,
    stock: 240,
    sold: 5640,
    isFlashDeal: true,
    isNew: false,
    isFeatured: true,
    tags: ["achar", "pantry"],
  },
  {
    slug: "shan-biryani-masala-bundle-of-6",
    name: "Shan Biryani Masala Bundle (6 packs)",
    brandSlug: "shan",
    categorySlug: "grocery",
    description:
      "Six packs of Shan's classic Bombay Biryani masala. Pantry-stock essential for every Pakistani kitchen.",
    price: 990,
    oldPrice: 1290,
    image: "product-pickle.png",
    images: ["product-pickle.png"],
    rating: "4.9",
    reviewCount: 2120,
    stock: 320,
    sold: 7240,
    isFlashDeal: false,
    isNew: false,
    isFeatured: true,
    tags: ["biryani", "masala"],
  },
  {
    slug: "tapal-danedar-loose-tea-950g",
    name: "Tapal Danedar Loose Tea 950g",
    brandSlug: "tapal",
    categorySlug: "grocery",
    description:
      "Granular black tea blended for that strong, milky doodh-patti exactly the way Pakistanis drink it morning, noon and night.",
    price: 1690,
    oldPrice: 1990,
    image: "product-tea.png",
    images: ["product-tea.png"],
    rating: "4.8",
    reviewCount: 980,
    stock: 180,
    sold: 4320,
    isFlashDeal: true,
    isNew: false,
    isFeatured: true,
    tags: ["chai", "tea"],
  },
  {
    slug: "national-chaat-masala-200g",
    name: "Chaat Masala 200g",
    brandSlug: "national",
    categorySlug: "grocery",
    description:
      "Tangy, spicy chaat masala for fruit chaat, dahi bhalla and your favourite street snacks.",
    price: 320,
    oldPrice: null,
    image: "product-pickle.png",
    images: ["product-pickle.png"],
    rating: "4.7",
    reviewCount: 540,
    stock: 420,
    sold: 1860,
    isFlashDeal: false,
    isNew: true,
    isFeatured: false,
    tags: ["masala", "snacks"],
  },
  {
    slug: "handwoven-jute-floor-cushion",
    name: "Handwoven Jute Floor Cushion",
    brandSlug: "khaadi",
    categorySlug: "home-lifestyle",
    description:
      "Hand-woven jute floor cushion with cotton-canvas back. A grounded statement piece for living rooms and reading corners.",
    price: 4290,
    oldPrice: 5290,
    image: "promo-band-1.jpg",
    images: ["promo-band-1.jpg"],
    rating: "4.6",
    reviewCount: 142,
    stock: 30,
    sold: 220,
    isFlashDeal: false,
    isNew: true,
    isFeatured: true,
    tags: ["home", "decor"],
  },
  {
    slug: "block-printed-cotton-bedsheet-king",
    name: "Block Printed Cotton Bedsheet — King",
    brandSlug: "sapphire",
    categorySlug: "home-lifestyle",
    description:
      "King-size cotton bedsheet with hand block-printed indigo motifs and two pillow covers. Soft, breathable and machine washable.",
    price: 5990,
    oldPrice: 7490,
    image: "promo-band-2.jpg",
    images: ["promo-band-2.jpg"],
    rating: "4.7",
    reviewCount: 320,
    stock: 56,
    sold: 480,
    isFlashDeal: true,
    isNew: false,
    isFeatured: true,
    tags: ["bedsheet", "home"],
  },
  {
    slug: "rose-amber-attar-12ml",
    name: "Rose & Amber Attar 12ml",
    brandSlug: "khaadi",
    categorySlug: "beauty",
    description:
      "Alcohol-free attar with Pakistani rose and warm amber. A grown-up, intimate scent perfect for evenings.",
    price: 2490,
    oldPrice: 2990,
    image: "promo-band-2.jpg",
    images: ["promo-band-2.jpg"],
    rating: "4.8",
    reviewCount: 410,
    stock: 88,
    sold: 1320,
    isFlashDeal: false,
    isNew: true,
    isFeatured: true,
    tags: ["attar", "fragrance"],
  },
  {
    slug: "saffron-honey-face-glow-serum",
    name: "Saffron & Honey Glow Serum 30ml",
    brandSlug: "khaadi",
    categorySlug: "beauty",
    description:
      "Lightweight serum with Pakistani saffron, raw honey and niacinamide. Gives an even, lit-from-within glow.",
    price: 1890,
    oldPrice: 2390,
    image: "promo-band-1.jpg",
    images: ["promo-band-1.jpg"],
    rating: "4.6",
    reviewCount: 220,
    stock: 140,
    sold: 760,
    isFlashDeal: true,
    isNew: true,
    isFeatured: false,
    tags: ["skincare", "serum"],
  },
  {
    slug: "organic-cotton-baby-jhabla-set-of-3",
    name: "Organic Cotton Baby Jhabla — Set of 3",
    brandSlug: "alkaram",
    categorySlug: "mother-baby",
    description:
      "Soft organic-cotton jhablas in newborn-friendly pastel prints. Side-tie closure, no buttons, gentle on baby's skin.",
    price: 1890,
    oldPrice: 2390,
    image: "summer-edit.jpg",
    images: ["summer-edit.jpg"],
    rating: "4.9",
    reviewCount: 540,
    stock: 120,
    sold: 1450,
    isFlashDeal: false,
    isNew: true,
    isFeatured: true,
    tags: ["baby", "newborn", "cotton"],
  },
  {
    slug: "muslin-swaddle-blanket-set-of-2",
    name: "Muslin Swaddle Blanket — Set of 2",
    brandSlug: "sapphire",
    categorySlug: "mother-baby",
    description:
      "Pre-washed double-layer muslin swaddles. Breathable, light and gets softer with every wash.",
    price: 2290,
    oldPrice: 2790,
    image: "summer-edit.jpg",
    images: ["summer-edit.jpg"],
    rating: "4.8",
    reviewCount: 280,
    stock: 90,
    sold: 620,
    isFlashDeal: true,
    isNew: false,
    isFeatured: false,
    tags: ["baby", "muslin"],
  },
];

const testimonials: InsertTestimonial[] = [
  {
    name: "Ayesha Tariq",
    city: "Lahore",
    rating: 5,
    comment:
      "Finally a Pakistani site that doesn't look like a 2008 spreadsheet. My Khaadi suit reached DHA in less than 48 hours, packed beautifully.",
    initials: "AT",
    position: 1,
  },
  {
    name: "Bilal Hussain",
    city: "Karachi",
    rating: 5,
    comment:
      "Ordered the Haier inverter AC at flash-deal price — installation was free in Clifton and the unit is genuinely silent. PakMart became my default.",
    initials: "BH",
    position: 2,
  },
  {
    name: "Sana Mehmood",
    city: "Islamabad",
    rating: 5,
    comment:
      "I do all my monthly grocery here now. Tapal Danedar, Shan masalas, achar — every single thing original and at better prices than my local store.",
    initials: "SM",
    position: 3,
  },
  {
    name: "Hamza Khan",
    city: "Rawalpindi",
    rating: 4,
    comment:
      "The Samsung A55 came sealed, PTA approved, with the imported charger. Cash on delivery worked smoothly with the rider.",
    initials: "HK",
    position: 4,
  },
  {
    name: "Fariha Iqbal",
    city: "Faisalabad",
    rating: 5,
    comment:
      "I bought my baby's organic jhabla set and it's the softest cotton I have touched. Stitching is clean, sizes run true. Will reorder.",
    initials: "FI",
    position: 5,
  },
  {
    name: "Usman Akhtar",
    city: "Multan",
    rating: 5,
    comment:
      "Finally somewhere I trust to ship Borjan chappals and Service loafers without a fake-stock surprise. Returns were painless when one size was off.",
    initials: "UA",
    position: 6,
  },
];

async function seed(): Promise<void> {
  await db.delete(productsTable);
  await db.delete(brandsTable);
  await db.delete(categoriesTable);
  await db.delete(testimonialsTable);

  await db.insert(categoriesTable).values(categories);
  await db.insert(brandsTable).values(brands);
  await db.insert(productsTable).values(products);
  await db.insert(testimonialsTable).values(testimonials);

  console.log(
    `Seeded ${categories.length} categories, ${brands.length} brands, ${products.length} products, ${testimonials.length} testimonials.`,
  );
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
